-- AlterTable
ALTER TABLE `victim` ADD COLUMN `attendingSchool` VARCHAR(191) NOT NULL DEFAULT '---',
    ADD COLUMN `contactNumber` VARCHAR(191) NOT NULL DEFAULT '---',
    ADD COLUMN `firstName` VARCHAR(191) NOT NULL DEFAULT '---',
    ADD COLUMN `gradeInSchool` VARCHAR(191) NULL DEFAULT '---',
    ADD COLUMN `homeVisitDates` VARCHAR(191) NULL DEFAULT '---',
    ADD COLUMN `lastName` VARCHAR(191) NOT NULL DEFAULT '---',
    ADD COLUMN `nameOfFather` VARCHAR(191) NULL DEFAULT '---',
    ADD COLUMN `nameOfMother` VARCHAR(191) NULL DEFAULT '---',
    ADD COLUMN `nameOfSchool` VARCHAR(191) NULL DEFAULT '---',
    ADD COLUMN `statusCase` VARCHAR(191) NOT NULL DEFAULT '---',
    ADD COLUMN `typeOfCase` VARCHAR(191) NULL DEFAULT '---';
