import { z } from "zod";

export const gbvInformationSchema = z.object({
  caseId: z.string().min(1),
  referredBy: z.string().min(1),
  anyService: z.string().min(1),
  redirected: z.string().min(1),
  droppedOutVictim: z.string().min(1),
  policeReport: z.string().min(1),
  protectionOrder: z.string().min(1),
  suicideAttempt: z.string().min(1),
  suicideMethod: z.string().nullable().optional(),
  suicideTime: z.string().nullable().optional(),
  noOfAttempts: z.string().nullable().optional(),
  satisfiedService: z.string().min(1),
  reasonNotSatisfied: z.string().nullable().optional(),
  medicalSupport: z.boolean().nullable().optional(),
  shelter: z.boolean().nullable().optional(),
  psychological: z.boolean().nullable().optional(),
  legalAssistance: z.boolean().nullable().optional(),
  securityProtection: z.boolean().nullable().optional(),
  vocTraining: z.boolean().nullable().optional(),
  infoLocal: z.boolean().nullable().optional(),
  emotionalSupport: z.boolean().nullable().optional(),
  otherSupport: z.string().nullable().optional(),
  rsMedicalSupport: z.boolean().nullable().optional(),
  rsShelter: z.boolean().nullable().optional(),
  rsPsychological: z.boolean().nullable().optional(),
  rsLegalAssistance: z.boolean().nullable().optional(),
  rsSecurityProtection: z.boolean().nullable().optional(),
  rsVocTraining: z.boolean().nullable().optional(),
  rsInfoLocal: z.boolean().nullable().optional(),
  rsEmotionalSupport: z.boolean().nullable().optional(),
  rsOtherSupport: z.string().nullable().optional(),
});

export const editGbvInformationSchema = z.object({
  referredBy: z.string().min(1),
  anyService: z.string().min(1),
  redirected: z.string().min(1),
  droppedOutVictim: z.string().min(1),
  policeReport: z.string().min(1),
  protectionOrder: z.string().min(1),
  suicideAttempt: z.string().min(1),
  suicideMethod: z.string().nullable().optional(),
  suicideTime: z.string().nullable().optional(),
  noOfAttempts: z.string().nullable().optional(),
  satisfiedService: z.string().min(1),
  reasonNotSatisfied: z.string().nullable().optional(),
  medicalSupport: z.boolean().nullable().optional(),
  shelter: z.boolean().nullable().optional(),
  psychological: z.boolean().nullable().optional(),
  legalAssistance: z.boolean().nullable().optional(),
  securityProtection: z.boolean().nullable().optional(),
  vocTraining: z.boolean().nullable().optional(),
  infoLocal: z.boolean().nullable().optional(),
  emotionalSupport: z.boolean().nullable().optional(),
  otherSupport: z.string().nullable().optional(),
  rsMedicalSupport: z.boolean().nullable().optional(),
  rsShelter: z.boolean().nullable().optional(),
  rsPsychological: z.boolean().nullable().optional(),
  rsLegalAssistance: z.boolean().nullable().optional(),
  rsSecurityProtection: z.boolean().nullable().optional(),
  rsVocTraining: z.boolean().nullable().optional(),
  rsInfoLocal: z.boolean().nullable().optional(),
  rsEmotionalSupport: z.boolean().nullable().optional(),
  rsOtherSupport: z.string().nullable().optional(),
});

export type TGbvInformationSchema = z.infer<typeof gbvInformationSchema>;
export type TEditGbvInformationSchema = z.infer<
  typeof editGbvInformationSchema
>;
